import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Link from "next/link";
import { useEffect } from "react";
export default function Home() {
  
  return (
    <div className={styles.container}>
      <Head>
        <title>Global Tech</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    
      <main className={styles.main}>
        
          <h1 className={styles.title}>Global Tech</h1>

          <Image src="/image1.jpg" alt="" width={350} height={350} ></Image>
          <p className={styles.description}>
            Welcome to Global Tech Blog Where you can find Everything about
            Internet Reveloution
          </p>
        
        <div className="blog">
          <h2>Popular B</h2>
          <div className="blogitem">
            <h3>Learn to JavaScript 2022</h3>
            <p>Learn how to styling on javeScript Pages</p>
          </div>
          <div className="blogitem">
            <h3>Learn to JavaScript 2022</h3>
            <p>Learn how to styling on javeScript Pages</p>
          </div>
          <div className="blogitem">
            <h3>Learn to JavaScript 2022</h3>
            <p>Learn how to styling on javeScript Pages</p>
          </div>
        </div>
      </main>

      <footer className={styles.footer}>
        
      </footer>
    </div>
  );
}
